export const ADD_USERNAME="ADD_USERNAME";
export const ADD_TRANSACTION="ADD_TRANSACTION";
export const UPDATE_AMOUNT="UPDATE_AMOUNT";
export const FETCH_ACCOUNTS_SUCCESS="FETCH_ACCOUNTS_SUCCESS";
export const FETCH_TRANSACTIONS_SUCCESS="FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_PAYEE_SUCCESS="FETCH_PAYEE_SUCCESS";
export const HANDLE_ERROR = "HANDLE_ERROR";
export const FETCH_REQUEST_DATA ="FETCH_REQUEST_DATA";
